# @see: https://github.com/marketplace/actions/setup-node-js-environment

name: CI

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22 ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --ignore-scripts --legacy-peer-deps
      - run: npm run all
